// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * The `trading_actions` row as the routes return it (§7).
 */
export type ActionRecord = {
    action_id: string;
    /**
     * `ALWAYS_ALLOW`, `PENDING`, `APPROVED`, or `DENIED` (R5 §3.3).
     */
    approval: string;
    created_at_ns: number;
    /**
     * Null exactly while `PENDING`.
     */
    decided_at_ns?: number | null;
    firing_id?: string | null;
    id: string;
    kind: string;
    /**
     * The response record, set when the command answers. Absent while the
     * order is pending approval, and `null` only while a concurrent duplicate
     * of the same `action_id` is still in flight.
     */
    outcome?: unknown;
    /**
     * `SESSION` or `TRIGGER` (R2 feature SPEC §6).
     */
    source: string;
    trigger_id?: string | null;
};

/**
 * One gated record of either kind, as `GET /approvals` and the decision route
 * answer it (§3.1). `id` is the `code_snapshots` or `trading_actions` row's own
 * UUID; `detail` is the kind's own object.
 */
export type Approval = {
    approval: string;
    /**
     * Null exactly while `PENDING`.
     */
    decided_at_ns?: number | null;
    desk_id: string;
    desk_name: string;
    detail: unknown;
    id: string;
    kind: string;
    requested_at_ns: number;
};

/**
 * The `memory_child` row plus the liveness that is never durable (§3).
 */
export type Child = {
    executable_path?: string | null;
    failure_code?: string | null;
    failure_message?: string | null;
    live: LiveState;
    pid?: number | null;
    /**
     * `UNCONFIGURED` | `AVAILABLE` | `UNAVAILABLE`.
     */
    state: string;
    validated_at_ns?: number | null;
};

/**
 * One desk row plus the read-time workspace derivation (§7.5). Field names and
 * omit-when-null behavior are the §6 `Desk` resource.
 */
export type Desk = {
    created_at_ns: number;
    failure_code?: string | null;
    failure_message?: string | null;
    id: string;
    name: string;
    /**
     * The desk's native-session pointers, filled by `GET /desks/{id}` only
     * (R3 feature SPEC §7); never stored on this row.
     */
    native_sessions?: unknown;
    ready_at_ns?: number | null;
    /**
     * `codex` | `claude`, the runtime this desk activates on (R3 §7).
     */
    selected_runtime: string;
    /**
     * `CREATING` | `READY` | `FAILED`.
     */
    state: string;
    workspace_path: string;
    /**
     * `OK` | `UNAVAILABLE`, derived for `READY` desks only; never stored.
     */
    workspace_status?: string | null;
    workspace_status_reason?: string | null;
};

/**
 * The one error envelope (§6, per R0-5): a stable SCREAMING_SNAKE code and an
 * English sentence, and nothing else. One `ToSchema` type that every route
 * declares for its non-2xx statuses, so a generated client carries the codes
 * typed (R5 feature SPEC §6.1).
 */
export type Envelope = {
    /**
     * The stable SCREAMING_SNAKE code.
     */
    code: string;
    /**
     * One English sentence.
     */
    message: string;
};

/**
 * The child's liveness (§6): memory only, `NOT_STARTED` after every start.
 */
export type LiveState = 'NOT_STARTED' | 'STARTING' | 'READY' | 'LOST';

/**
 * The `memory_provider` row, secrets-free by construction (§3).
 */
export type Provider = {
    api_key_present: boolean;
    base_url?: string | null;
    embedding_locked_at_ns?: number | null;
    embedding_model?: string | null;
    llm_model?: string | null;
};

/**
 * The `GET`/`PUT /settings/policies` body (§2).
 */
export type Resource = {
    delivery_mode: string;
    paper_order_policy: string;
    /**
     * Steering is reserved and never offered (root §11.2, per D70).
     */
    steer_available: boolean;
    trigger_code_policy: string;
    updated_at_ns: number;
};

/**
 * One `runtimes` row (§8), secrets-free by construction.
 */
export type Runtime = {
    executable_path?: string | null;
    failure_code?: string | null;
    failure_message?: string | null;
    runtime: string;
    /**
     * `UNDISCOVERED` | `AVAILABLE` | `UNAVAILABLE`.
     */
    state: string;
    validated_at_ns?: number | null;
    version?: string | null;
};

/**
 * `GET /memory` (§3): both installation rows in the order the CLI prints them.
 */
export type Status = {
    child: Child;
    provider: Provider;
};

export type ApprovalsData = {
    body?: never;
    path?: never;
    query?: {
        state?: string | null;
    };
    url: '/approvals';
};

export type ApprovalsErrors = {
    400: Envelope;
    401: Envelope;
};

export type ApprovalsError = ApprovalsErrors[keyof ApprovalsErrors];

export type ApprovalsResponses = {
    200: unknown;
};

export type ApprovalData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/approvals/{id}';
};

export type ApprovalErrors = {
    401: Envelope;
    404: Envelope;
};

export type ApprovalError = ApprovalErrors[keyof ApprovalErrors];

export type ApprovalResponses = {
    200: Approval;
};

export type ApprovalResponse = ApprovalResponses[keyof ApprovalResponses];

export type ListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/desks';
};

export type ListErrors = {
    401: Envelope;
};

export type ListError = ListErrors[keyof ListErrors];

export type ListResponses = {
    200: unknown;
};

export type CreateData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/desks';
};

export type CreateErrors = {
    400: Envelope;
    401: Envelope;
    409: Envelope;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    201: Desk;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type ShowData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}';
};

export type ShowErrors = {
    401: Envelope;
    404: Envelope;
};

export type ShowError = ShowErrors[keyof ShowErrors];

export type ShowResponses = {
    200: Desk;
};

export type ShowResponse = ShowResponses[keyof ShowResponses];

export type DecideApprovalData = {
    body: unknown;
    path: {
        desk_id: string;
        id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/approvals/{id}';
};

export type DecideApprovalErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type DecideApprovalError = DecideApprovalErrors[keyof DecideApprovalErrors];

export type DecideApprovalResponses = {
    200: Approval;
};

export type DecideApprovalResponse = DecideApprovalResponses[keyof DecideApprovalResponses];

export type ShowFiringData = {
    body?: never;
    path: {
        desk_id: string;
        firing_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/firings/{firing_id}';
};

export type ShowFiringErrors = {
    401: Envelope;
    404: Envelope;
};

export type ShowFiringError = ShowFiringErrors[keyof ShowFiringErrors];

export type ShowFiringResponses = {
    200: unknown;
};

export type HistoryActionsData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/history/actions';
};

export type HistoryActionsErrors = {
    401: Envelope;
    404: Envelope;
};

export type HistoryActionsError = HistoryActionsErrors[keyof HistoryActionsErrors];

export type HistoryActionsResponses = {
    200: unknown;
};

export type HistoryCyclesData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/history/cycles';
};

export type HistoryCyclesErrors = {
    401: Envelope;
    404: Envelope;
};

export type HistoryCyclesError = HistoryCyclesErrors[keyof HistoryCyclesErrors];

export type HistoryCyclesResponses = {
    200: unknown;
};

export type HistoryFillsData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/history/fills';
};

export type HistoryFillsErrors = {
    401: Envelope;
    404: Envelope;
};

export type HistoryFillsError = HistoryFillsErrors[keyof HistoryFillsErrors];

export type HistoryFillsResponses = {
    200: unknown;
};

export type HistoryOrdersData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/history/orders';
};

export type HistoryOrdersErrors = {
    401: Envelope;
    404: Envelope;
};

export type HistoryOrdersError = HistoryOrdersErrors[keyof HistoryOrdersErrors];

export type HistoryOrdersResponses = {
    200: unknown;
};

export type BookData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/market/book';
};

export type BookErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type BookError = BookErrors[keyof BookErrors];

export type BookResponses = {
    200: unknown;
};

export type InstrumentsData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/market/instruments';
};

export type InstrumentsErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
};

export type InstrumentsError = InstrumentsErrors[keyof InstrumentsErrors];

export type InstrumentsResponses = {
    200: unknown;
};

export type QuotesData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/market/quotes';
};

export type QuotesErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type QuotesError = QuotesErrors[keyof QuotesErrors];

export type QuotesResponses = {
    200: unknown;
};

export type DeskMemoryData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/memory';
};

export type DeskMemoryErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type DeskMemoryError = DeskMemoryErrors[keyof DeskMemoryErrors];

export type DeskMemoryResponses = {
    200: unknown;
};

export type MemoryRecallData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/memory/recall';
};

export type MemoryRecallErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    422: Envelope;
    502: Envelope;
    503: Envelope;
    504: Envelope;
};

export type MemoryRecallError = MemoryRecallErrors[keyof MemoryRecallErrors];

export type MemoryRecallResponses = {
    200: unknown;
};

export type MemoryReflectData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/memory/reflect';
};

export type MemoryReflectErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    422: Envelope;
    502: Envelope;
    503: Envelope;
    504: Envelope;
};

export type MemoryReflectError = MemoryReflectErrors[keyof MemoryReflectErrors];

export type MemoryReflectResponses = {
    200: unknown;
};

export type MemoryRetainData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/memory/retain';
};

export type MemoryRetainErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    422: Envelope;
    502: Envelope;
    503: Envelope;
    504: Envelope;
};

export type MemoryRetainError = MemoryRetainErrors[keyof MemoryRetainErrors];

export type MemoryRetainResponses = {
    200: unknown;
};

export type OpenOrdersData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/orders';
};

export type OpenOrdersErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type OpenOrdersError = OpenOrdersErrors[keyof OpenOrdersErrors];

export type OpenOrdersResponses = {
    200: unknown;
};

export type SubmitOrderData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/orders';
};

export type SubmitOrderErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type SubmitOrderError = SubmitOrderErrors[keyof SubmitOrderErrors];

export type SubmitOrderResponses = {
    200: ActionRecord;
    201: ActionRecord;
    202: ActionRecord;
};

export type SubmitOrderResponse = SubmitOrderResponses[keyof SubmitOrderResponses];

export type CancelOrderData = {
    body: unknown;
    path: {
        desk_id: string;
        client_order_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/orders/{client_order_id}/cancel';
};

export type CancelOrderErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type CancelOrderError = CancelOrderErrors[keyof CancelOrderErrors];

export type CancelOrderResponses = {
    200: ActionRecord;
};

export type CancelOrderResponse = CancelOrderResponses[keyof CancelOrderResponses];

export type PositionsData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/positions';
};

export type PositionsErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    503: Envelope;
};

export type PositionsError = PositionsErrors[keyof PositionsErrors];

export type PositionsResponses = {
    200: unknown;
};

export type ListPromptsData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/prompts';
};

export type ListPromptsErrors = {
    401: Envelope;
    404: Envelope;
};

export type ListPromptsError = ListPromptsErrors[keyof ListPromptsErrors];

export type ListPromptsResponses = {
    200: unknown;
};

export type ShowPromptData = {
    body?: never;
    path: {
        desk_id: string;
        prompt_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/prompts/{prompt_id}';
};

export type ShowPromptErrors = {
    401: Envelope;
    404: Envelope;
};

export type ShowPromptError = ShowPromptErrors[keyof ShowPromptErrors];

export type ShowPromptResponses = {
    200: unknown;
};

export type RetryData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/retry';
};

export type RetryErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
};

export type RetryError = RetryErrors[keyof RetryErrors];

export type RetryResponses = {
    200: Desk;
};

export type RetryResponse = RetryResponses[keyof RetryResponses];

export type SessionData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/session';
};

export type SessionErrors = {
    401: Envelope;
    404: Envelope;
};

export type SessionError = SessionErrors[keyof SessionErrors];

export type SessionResponses = {
    200: unknown;
};

export type SessionActivateData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/session/activate';
};

export type SessionActivateErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
};

export type SessionActivateError = SessionActivateErrors[keyof SessionActivateErrors];

export type SessionActivateResponses = {
    202: unknown;
};

export type SessionExitData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/session/exit';
};

export type SessionExitErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    502: Envelope;
};

export type SessionExitError = SessionExitErrors[keyof SessionExitErrors];

export type SessionExitResponses = {
    202: unknown;
};

export type SessionHookData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/session/hook';
};

export type SessionHookErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
};

export type SessionHookError = SessionHookErrors[keyof SessionHookErrors];

export type SessionHookResponses = {
    202: unknown;
};

export type SessionInterruptData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/session/interrupt';
};

export type SessionInterruptErrors = {
    401: Envelope;
    404: Envelope;
    409: Envelope;
    502: Envelope;
};

export type SessionInterruptError = SessionInterruptErrors[keyof SessionInterruptErrors];

export type SessionInterruptResponses = {
    202: unknown;
};

export type SessionSwitchData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/session/switch';
};

export type SessionSwitchErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
    502: Envelope;
};

export type SessionSwitchError = SessionSwitchErrors[keyof SessionSwitchErrors];

export type SessionSwitchResponses = {
    200: unknown;
};

export type ListTriggersData = {
    body?: never;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/triggers';
};

export type ListTriggersErrors = {
    401: Envelope;
    404: Envelope;
};

export type ListTriggersError = ListTriggersErrors[keyof ListTriggersErrors];

export type ListTriggersResponses = {
    200: unknown;
};

export type CreateTriggerData = {
    body: unknown;
    path: {
        desk_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/triggers';
};

export type CreateTriggerErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
};

export type CreateTriggerError = CreateTriggerErrors[keyof CreateTriggerErrors];

export type CreateTriggerResponses = {
    201: unknown;
};

export type DeleteTriggerData = {
    body?: never;
    path: {
        desk_id: string;
        trigger_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/triggers/{trigger_id}';
};

export type DeleteTriggerErrors = {
    401: Envelope;
    404: Envelope;
};

export type DeleteTriggerError = DeleteTriggerErrors[keyof DeleteTriggerErrors];

export type DeleteTriggerResponses = {
    200: unknown;
};

export type ShowTriggerData = {
    body?: never;
    path: {
        desk_id: string;
        trigger_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/triggers/{trigger_id}';
};

export type ShowTriggerErrors = {
    401: Envelope;
    404: Envelope;
};

export type ShowTriggerError = ShowTriggerErrors[keyof ShowTriggerErrors];

export type ShowTriggerResponses = {
    200: unknown;
};

export type PatchTriggerData = {
    body: unknown;
    path: {
        desk_id: string;
        trigger_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/triggers/{trigger_id}';
};

export type PatchTriggerErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
    409: Envelope;
};

export type PatchTriggerError = PatchTriggerErrors[keyof PatchTriggerErrors];

export type PatchTriggerResponses = {
    200: unknown;
};

export type TriggerFiringsData = {
    body?: never;
    path: {
        desk_id: string;
        trigger_id: string;
    };
    query?: never;
    url: '/desks/{desk_id}/triggers/{trigger_id}/firings';
};

export type TriggerFiringsErrors = {
    401: Envelope;
    404: Envelope;
};

export type TriggerFiringsError = TriggerFiringsErrors[keyof TriggerFiringsErrors];

export type TriggerFiringsResponses = {
    200: unknown;
};

export type EventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Only this desk's rows
         */
        desk_id?: string;
        /**
         * Page back from this cursor
         */
        before?: string;
        /**
         * 1 to 500; 100 by omission
         */
        limit?: number;
    };
    url: '/events';
};

export type EventsErrors = {
    400: Envelope;
    401: Envelope;
    403: Envelope;
};

export type EventsError = EventsErrors[keyof EventsErrors];

export type EventsResponses = {
    /**
     * One page of the tail, newest first
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthErrors = {
    401: Envelope;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    200: unknown;
};

export type MemoryStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/memory';
};

export type MemoryStatusErrors = {
    401: Envelope;
    503: Envelope;
};

export type MemoryStatusError = MemoryStatusErrors[keyof MemoryStatusErrors];

export type MemoryStatusResponses = {
    200: Status;
};

export type MemoryStatusResponse = MemoryStatusResponses[keyof MemoryStatusResponses];

export type MemoryDiscoverData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/memory/discover';
};

export type MemoryDiscoverErrors = {
    400: Envelope;
    401: Envelope;
    503: Envelope;
};

export type MemoryDiscoverError = MemoryDiscoverErrors[keyof MemoryDiscoverErrors];

export type MemoryDiscoverResponses = {
    200: Child;
};

export type MemoryDiscoverResponse = MemoryDiscoverResponses[keyof MemoryDiscoverResponses];

export type MemoryProviderData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/memory/provider';
};

export type MemoryProviderErrors = {
    400: Envelope;
    401: Envelope;
    409: Envelope;
    502: Envelope;
    503: Envelope;
};

export type MemoryProviderError = MemoryProviderErrors[keyof MemoryProviderErrors];

export type MemoryProviderResponses = {
    200: Provider;
};

export type MemoryProviderResponse = MemoryProviderResponses[keyof MemoryProviderResponses];

export type MemoryModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/memory/provider/models';
};

export type MemoryModelsErrors = {
    401: Envelope;
    409: Envelope;
    502: Envelope;
    503: Envelope;
    504: Envelope;
};

export type MemoryModelsError = MemoryModelsErrors[keyof MemoryModelsErrors];

export type MemoryModelsResponses = {
    200: unknown;
};

export type MemoryRetryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/memory/retry';
};

export type MemoryRetryErrors = {
    401: Envelope;
    503: Envelope;
};

export type MemoryRetryError = MemoryRetryErrors[keyof MemoryRetryErrors];

export type MemoryRetryResponses = {
    200: Child;
};

export type MemoryRetryResponse = MemoryRetryResponses[keyof MemoryRetryResponses];

export type QuitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quit';
};

export type QuitErrors = {
    401: Envelope;
};

export type QuitError = QuitErrors[keyof QuitErrors];

export type QuitResponses = {
    202: unknown;
};

export type RuntimesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/runtimes';
};

export type RuntimesErrors = {
    401: Envelope;
};

export type RuntimesError = RuntimesErrors[keyof RuntimesErrors];

export type RuntimesResponses = {
    200: unknown;
};

export type RuntimeDiscoverData = {
    body: unknown;
    path: {
        runtime: string;
    };
    query?: never;
    url: '/runtimes/{runtime}/discover';
};

export type RuntimeDiscoverErrors = {
    400: Envelope;
    401: Envelope;
    404: Envelope;
};

export type RuntimeDiscoverError = RuntimeDiscoverErrors[keyof RuntimeDiscoverErrors];

export type RuntimeDiscoverResponses = {
    200: Runtime;
};

export type RuntimeDiscoverResponse = RuntimeDiscoverResponses[keyof RuntimeDiscoverResponses];

export type RuntimeRetryData = {
    body?: never;
    path: {
        runtime: string;
    };
    query?: never;
    url: '/runtimes/{runtime}/retry';
};

export type RuntimeRetryErrors = {
    401: Envelope;
    404: Envelope;
};

export type RuntimeRetryError = RuntimeRetryErrors[keyof RuntimeRetryErrors];

export type RuntimeRetryResponses = {
    200: Runtime;
};

export type RuntimeRetryResponse = RuntimeRetryResponses[keyof RuntimeRetryResponses];

export type PoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/policies';
};

export type PoliciesErrors = {
    401: Envelope;
};

export type PoliciesError = PoliciesErrors[keyof PoliciesErrors];

export type PoliciesResponses = {
    200: Resource;
};

export type PoliciesResponse = PoliciesResponses[keyof PoliciesResponses];

export type PutPoliciesData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/settings/policies';
};

export type PutPoliciesErrors = {
    400: Envelope;
    401: Envelope;
    409: Envelope;
};

export type PutPoliciesError = PutPoliciesErrors[keyof PutPoliciesErrors];

export type PutPoliciesResponses = {
    200: Resource;
};

export type PutPoliciesResponse = PutPoliciesResponses[keyof PutPoliciesResponses];
